# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@6004246f47ab62d32be025ce173b241cd84ac58e
      uses: codecov/codecov-action@v1.0.13
      with:
        name: \@aujsf/core
        file: packages/core/coverage/coverage-final.json
        fail_ci_if_error: true
